### ISSUE TITLE
Cant get it to run

### ISSUE THREAD

**Issue by Donaldini** [glen-84/vscode-sass-lint#23]
I just installed _Sass Lint 1.0.2_ in my VS Code, but couldn't get any indication of any linting happening.

When I tried command line on the file I have open, there were some issues, but never in the IDE.

![image](https://user-images.githubusercontent.com/2185680/41160292-7a8bdebe-6b2f-11e8-9695-dde38a221292.png)

Information about my setup:

OS version: **Mac OS X High Sierra 10.13.4**
VS Code version: **1.23.1**
Node.js version: **6.2.2**
sass-lint version: **1.12.1 (global)**
How many sass/scss files open: **2**

Extension configuration:
![image](https://user-images.githubusercontent.com/2185680/41160145-123ed17c-6b2f-11e8-9b99-47038a25afa1.png)

the path above to the _.sass-lint.yml_ is a working path. When I copy paste it in a terminal screen after a `vi` command I get the file content, so that shouldn't be an issue.

**Comment by glen-84** [comment]
Are you able to upload your `.sass-lint.yml` file?

**Comment by Donaldini** [comment]
Here you go: 

```
options:
  formatter: stylish
  convention-explanation: 'SASS Standard - Protime adjustment'
files:
  include:
    - 'drool/**/*.s+(a|c)ss'
    - 'drool-lib/**/*.s+(a|c)ss'
    - 'app/**/*.s+(a|c)ss'
rules:
  # Extends
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 2

  # Mixins
  mixins-before-declarations: 2

  # Line Spacing
  one-declaration-per-line: 2
  empty-line-between-blocks: 2
  single-line-per-selector: 2

  # Disallows
  declarations-before-nesting: 2
  no-color-keywords: 2
  no-color-literals: 2
  no-css-comments: 0
  no-debug: 2
  no-duplicate-properties: 2
  no-empty-rulesets: 2
  no-extends: 0
  no-ids: 2
  no-important: 0                 # Should be an error, but requires some changes on legacy files
  no-invalid-hex: 2
  no-mergeable-selectors: 2
  no-misspelled-properties: 2
  no-qualifying-elements:
    - 2
    -
      allow-element-with-attribute: true
      allow-element-with-class: true
      allow-element-with-id: false

  no-trailing-zero: 2
  no-transition-all: 0            # Should be an error, performance impact and unpredictable
  no-url-protocols: 0
  no-url-domains: 0
  no-vendor-prefixes: 2
  no-warn: 2
  property-units: 0

  # Nesting
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0

  # Name Formats
  class-name-format:
    - 0                         # NO warning, this is unusable because of the amount of warnings, we want to set this as an error once all components have been converted to CSS modules
    -
      convention: 'camelcase'

  function-name-format: 2
  id-name-format: 0
  mixin-name-format: 2
  placeholder-name-format:
    - 1
    -
      convention: 'camelcase'

  variable-name-format: 0
  clean-import-paths: 0

  # Style Guide
  bem-depth: 0
  border-zero:
    - 2
    -
      convention: 'none'

  brace-style:
    - 2
    - 
      style: '1tbs'
      allow-single-line: true

  empty-args: 2
  hex-length: 2
  hex-notation: 2
  indentation:
    - 2
    - 
      size: 4

  leading-zero: 0
  nesting-depth:
    - 2
    -
      max-depth: 5

  property-sort-order:
    - 2
    -
      order: 'concentric'

  quotes: 2
  shorthand-values: 2
  url-quotes: 2
  variable-for-property: 2
  zero-unit: 2

  # Inner Spacing
  space-after-comma: 2
  space-before-colon: 2
  space-after-colon: 2
  space-before-brace: 2
  space-before-bang: 2
  space-after-bang: 2
  space-between-parens: 2
  space-around-operator: 2

  # Final Items
  trailing-semicolon: 2
  final-newline: 2
```

**Comment by glen-84** [comment]
I'm not able to reproduce this on Windows, and I don't have access to a Mac. 😐 

Have you tried:

1. Copying or symlinking the `.sass-lint.yml` file into your project (and removing the `sasslint.configFile` setting)
2. When running sass-lint from the command line, using the `-c` option to specify the path to your configuration file (I don't know whether the output that you're seeing is from the default configuration or your own configuration)
3. Removing the files/include section from your configuration, in case that is causing problems

**Comment by Donaldini** [comment]
In the editor I still can't see any errors, command line has always worked.
I tried your steps anyway by
- removing all user settings related to sass-lint
- Added sass-lint file to my project
- double checked command line

![example](https://user-images.githubusercontent.com/2185680/41525238-94f54cdc-72e0-11e8-80e2-76b3606b9273.png)

There was no difference in results when I tried with or without the reference to the local sass-lint file:

> sass-lint 'src/css/profile.scss' -v -q
> sass-lint -c '.sass-lint.yml' 'src/css/profile.scss' -v -q

Both worked and gave the same amount of errors in console, but none in VS Code.

**Comment by glen-84** [comment]
Did you try without this part in your config file?

```yaml
files:
  include:
    - 'drool/**/*.s+(a|c)ss'
    - 'drool-lib/**/*.s+(a|c)ss'
    - 'app/**/*.s+(a|c)ss'
```

If it still doesn't work, it'd help to have a small project that I could use to test a similar setup on my PC.
