### ISSUE TITLE
Extension not working

### ISSUE THREAD

**Issue by ghKZ** [glen-84/vscode-sass-lint#26]
Hi,

After installing the extension and making sure that "sass-lint" is available, both globally as well as locally, the extension still seems to fail to load/run/lint.

Our project structure:
- root
- .sass-lint.yml
-- packages
--- src
---- .scss file

When we run the sass-linter manually with `sass-lint '**/*.scss' -v`, it picks up all the files to lint correctly and outputs any of the issues in the terminal.

Relevant information:
- MacOS High Sierra 10.13.5
- VSCode 1.25.0
- VSCode Sass Lint extension 1.0.2
- local sass-lint 1.12.1
- global sass-lint 1.12.1
- VSCode Extension Host output:
```
[2018-07-10 16:44:51.143] [exthost1] [info] ExtensionService#_doActivateExtension glen-84.sass-lint {"startup":false,"activationEvent":"onLanguage:scss"}
[2018-07-10 16:44:51.143] [exthost1] [info] ExtensionService#loadCommonJSModule /Users/<account-name>/.vscode/extensions/glen-84.sass-lint-1.0.2/out/extension
```
- .sass-lint.yml content:
```
files:
  include: 'sass/**/*.s+(a|c)ss'
  ignore: 'node_modules/**'

rules:
  class-name-format:
    - 2
    - convention: hyphenatedlowercase
  single-line-per-selector: 1
  space-around-operator: 2
  space-before-brace: 2
  space-before-bang: 2
  space-before-colon: 2
  space-between-parens: 2
  zero-unit:
    - 2
```

Things we've tried:
- move the sass-lint config file into the "package" folder, next to the "scss" file
- setting the path to config file in VSCode settings

Let me know if you require any additional information.

**Comment by dzienisz** [comment]
I have the same problem in newest vs code 1.25.0.

**Comment by glen-84** [comment]
```yml
files:
  include: 'sass/**/*.s+(a|c)ss'
  ignore: 'node_modules/**'
```

Where is the `sass` folder in your project structure?
