### ISSUE TITLE
VS Code doesn't see extension config

### ISSUE THREAD

**Issue by AndreyYevtukhov** [glen-84/vscode-sass-lint#37]
Hi!

We've tried to configure `vscode-sass-lint` extension today, but failed.
And we couldn't figure out, what is wrong :(
We aren't getting errors, whatever we do :(

Our config looks like this:

![1](https://user-images.githubusercontent.com/14858875/68947057-3190ad80-07bd-11ea-98b8-4f440a7a5ffc.jpg)

---

Some additional information:
1. `node_modules` contains sass-lint package, v.6.9.0
2. both `.yml` and `node_modules` paths are correct
3. VS Code restarts does nothing
4. opened `.scss` file contain errors (for testing)
5. Running linter from console (using `sass-lint --verbose`) works fine (it shows output and errors)

---

I'm sure, we're missing something, but can't figure out what by ourselves :(

**Comment by AndreyYevtukhov** [comment]
Fixed by changing file paths in `.yml` config file:

was: (wrong, BUT worked, when running `sass-lint`)
```
# File Options
files:
  include: './**/*.scss'
  ignore:
    - './node_modules/**/*.*'
    - './libs/**/*.*'
```

now: (correct, +also works when running `sass-lint`)
```
# File Options
files:
  include: '**/*.scss'
  ignore:
    - 'node_modules/**/*.*'
    - 'libs/**/*.*'
```

---
As I understood, something caused invalid path resolving, when using files paths with current directory `./` part.
