### ISSUE TITLE
Keeps crashing

### ISSUE THREAD

**Issue by tswaters** [glen-84/vscode-sass-lint#4]
I keep getting the following flash shown:

> The Sass Lint server crashed 5 times in the last 3 minutes. The server will not be restarted.

I can't see any stack trace or anything but the vscode instance must be restarted to get warnings and errors from this extension again.

This is on Windows 10.  
sass-lint: v.1.9.0
node: v6.3.0
vscode: 1.4.0
there are 4 sass files in the project.

It will happen as I'm making changes to the sass files attempting to fix up the problems.

My config file:

``` yml
files:
  include: 'assets/sass/*.s+(a|c)ss'
rules:
  property-sort-order:
  - 1
  -
    order: 'smacss'
```

And relevant settings in vscode settings:

``` json
{
  "scss.validate": false,
  "sasslint.enable": true,
  "sasslint.configFile": ".sass-lint.yml"
}
```

I wish I could be of more help - do you know of a way I can get the stack trace from the language service?  The only thing the vscode dev tools report is a console.error in messageService.js.
