### ISSUE TITLE
vscode freeze up

### ISSUE THREAD

**Issue by DaClan008** [glen-84/vscode-sass-lint#5]
My vscode editor freezes up.  Or at least will not save any files, and I can hear my processor fan working more than usual at times when this happens.  I believe it is related to this extension, but am unable or don't know how to trouble shoot any further.

**Environment changes**
Changes that took place from the  day before when everything was working great.
- I had a windows update;
- I believe vs Code also updated and 
- I was prompted to update vscode-sass-lint, which I did.  
  This is when the problems started happening.  Not sure or can't remember of any other changes

**Actions Takens**
Since then I have:
- updated sass-lint -g (not sure if this is the linter vscode uses);
- updated node and 
- updated npm just in case.

**Aside**
I am also sitting with quite a few error messages produced by the sass-linter.  This relates to indentation errors when using @media queries.  I have logged this error with sass-lint hub, as I believe it is a sass-lint issue.  The code compiles correctly though, so apart from being highly annoying, the error messages is manageable until their next update which hopefully is soon.  I am not sure if this is causing vscode-sass-lint to fail aswell?  For more info on this issue, see their [issue list#591](https://github.com/sasstools/sass-lint/issues/591#issuecomment-253175405).

**Further**
At one stage yesterday vs Code logged a message at the top of the screen indicating that it had stopped operations of this extension as it has failed to respond more than 5 times.  That was great for me as I was able to start working again.  Well, that was until I had to restart vs code for another project and the problems returned.

**next step**
My only option now is the uninstall vscode-sass-lint, or switch to Atom.

**Comment by DaClan008** [comment]
I have also now commented on an [issue with vscode](https://github.com/Microsoft/vscode/issues/13649#issuecomment-253438635) where this morning I see another person having similar issues with other extensions.  I am not sure if vscode made an update and now the extensions must follow suit (i.e. extension issue) or a vscode issue.

**Comment by glen-84** [comment]
Hi Jan,

Could you please provide some additional information, such as:
- OS version
- VS Code version
- Node.js version
- sass-lint version
- How many sass/scss files open
- Extension configuration
- sass-lint configuration
- etc.

Also, could you maybe try the "lint on save" option?

**Comment by DaClan008** [comment]
Hi Glen

I do not think it is necessary anymore as it all seem to be running stable, at least at this moment.

I must say I am disapointed in vscode and [bpasero](https://github.com/Microsoft/vscode/issues/13649#issuecomment-253506602) that tried to blame extensions for the problem, which I now firmly believe was a vscode issue.  I updated my vscode from 1.6.0 to 1.6.1 on Friday, and reinstalled sass lint.  The linting has worked perfectly fine since then.  However I haven't worked extensively hard with it yet, so will keep an eye on it and open another issue if problems start up again.  [ps.  vscode-sass-lint was only uninstalled to allow me to work]

Thank you for your reply.

Just in case, I will provide the information requested:
- OS Version - windows 10 V1607 (build 14393.321)
- VS Code - at time problems occured (v 1.6.0) currently (v 1.6.1)
- node.js - v 6.7.0
- npm - v 3.10.8
- sass-lint - v 1.9.1 (well that is the sass-lint which is installed globally - not sure if vscode is using this sass-lint, or its own)
-  sass files - depends, but I guess a maximum of 10 usually
- I haven't changed any Extension configuration settings

and my sass-lint configuration: 

``` yml
options:
  formatter: stylish
files:
  include: '**/*.s+(a|c)ss'

rules:   
    empty-line-between-blocks: 1
    no-css-comments: 0
    one-declaration-per-line: 0
    single-line-per-selector: 0
    indentation:
    - 2
    - size: 4

    nesting-depth: 
    - 2
    - max-depth: 4

    class-name-format: 
    - 2
    - allow-leading-underscore: true
    - ignore:
      - 

    no-transition-all: 0
    no-ids: 0
    no-color-literals: 0
    placeholder-in-extend: 0
    force-element-nesting: 0
```
