### ISSUE TITLE
.scss-lint.yml is ignored.

### ISSUE THREAD

**Issue by iliran11** [glen-84/vscode-sass-lint#9]
## Enviroment
* **VS Code:**  1.10.2
* **Sass Lint:**   0.0.3

## problem summary

sass linter works, and seems to ignore `.scss-lint.yml`. the file is present on the root path of the project.

### sample Scss File
```scss
        #balance-header {
            margin-top: 0;
        }
```

* **got the following errors:** 
both of the errors are not justified by my configuration file, as i want to allow ID selector and specified Indentation of 4.

```
file: 'file:///c%3A/projects/banking/src/sass/dashboard.scss'
severity: 'Warning'
message: 'ID selectors not allowed'
at: '2,9'
source: 'sass-lint'
```

```
file: 'file:///c%3A/projects/banking/src/sass/dashboard.scss'
severity: 'Warning'
message: 'Expected indentation of 0 space but found 8.'
at: '2,9'
source: 'sass-lint'1
```

### .scss-lint.yml: 
```yml
linters:
    PropertySortOrder:
        enabled: false

    DuplicateProperty:
        enabled: false

    Indentation:
        allow_non_nested_indentation: true
        width: 4

    SelectorDepth:
        max_depth: 16

    SpaceAfterPropertyColon:
        enabled: true

    Compass::*:
        enabled: true

    NestingDepth:
        enabled: true
        max_depth: 16
        # ignore_parent_selectors: true

    IdSelector:
        enabled: true

    ImportantRule:
        enabled: false

    QualifyingElement:
        allow_element_with_attribute: true
        allow_element_with_class: true
        allow_element_with_id: true

    PlaceholderInExtend:
      enabled: false

    Comment:
        enabled: false

    VendorPrefix:
        excluded_identifiers: ['touch-action']

    SelectorFormat:
        enabled: true
        convention: hyphenated_BEM

    SpaceBetweenParens:
        enabled: false

    SpaceAroundOperator:
        enabled: false

    StringQuotes:
        enabled: false

    FinalNewline:
        enabled: false

    NameFormat:
        enabled: false
```
